import { Router } from 'express';
import BankCardController from '~/controllers/bank_card.controller';
import DependencyInjection from '~/di/di';
import AuthValidation from '~/middlewares/auth.middleware';
import { BankValidate as BankAccountValidation } from '~/middlewares/bank.middleware';
import CommonValidation from '~/middlewares/common.middlewares';
const bankAccountController = DependencyInjection.get<BankCardController>(BankCardController);
const router = Router();
const authValidation = DependencyInjection.get<AuthValidation>(AuthValidation);
const commonValidation = DependencyInjection.get<CommonValidation>(CommonValidation);
const bankAccountValidation = DependencyInjection.get<BankAccountValidation>(BankAccountValidation);
router.use(authValidation.accessTokenValidation);
router.post('/', bankAccountValidation.addBankCard, bankAccountController.addBankCard);
router.get('/', bankAccountController.getAllBankAccount);
router.get('/primary', bankAccountController.getPrimaryBankCard);
router.get('/:id', commonValidation.validateId, bankAccountController.getBankCardById);
router.delete('/:id', commonValidation.validateId, bankAccountController.deleteBankCard);
router.put('/:id/mark-as-primary', commonValidation.validateId, bankAccountController.markAsPrimaryBankCard);
export default router;
