import { Router } from 'express';
import BankAccountController from '~/controllers/bank_account.controller';
import DependencyInjection from '~/di/di';
import AuthValidation from '~/middlewares/auth.middleware';
import { BankAccountValidate as BankAccountValidation } from '~/middlewares/bank_account.middleware';
import CommonValidation from '~/middlewares/common.middlewares';
const bankAccountController = DependencyInjection.get<BankAccountController>(BankAccountController);
const router = Router();
const authValidation = DependencyInjection.get<AuthValidation>(AuthValidation);
const commonValidation = DependencyInjection.get<CommonValidation>(CommonValidation);
const bankAccountValidation = DependencyInjection.get<BankAccountValidation>(BankAccountValidation);
router.use(authValidation.accessTokenValidation);
router.post('/', bankAccountValidation.createBankAccount, bankAccountController.createBankAccount);
router.get('/', bankAccountController.getAllBankAccount);
router.get('/primary', bankAccountController.getPrimaryBankAccount);
router.get('/:id', commonValidation.validateId, bankAccountController.getBankAccountById);
router.delete('/:id', commonValidation.validateId, bankAccountController.deleteBankAccount);
router.put('/:id/mark-as-primary', commonValidation.validateId, bankAccountController.markAsPrimaryBankAccount);
export default router;
