import { Router } from 'express';
import BlogController from '../controllers/blog.controller';
import AuthValidation from '../middlewares/auth.middleware';
import DependencyInjection from '../di/di';
import CommonValidation from '~/middlewares/common.middlewares';
const blogController = DependencyInjection.get<BlogController>(BlogController);
const authValidation = DependencyInjection.get<AuthValidation>(AuthValidation);
const commonValidation = DependencyInjection.get<CommonValidation>(CommonValidation);
const router = Router();
router.get('/', authValidation.getUserByTokenIfExist, blogController.getAllBlog);
router.get('/:id', commonValidation.validateId, authValidation.getUserByTokenIfExist, blogController.getBlogById);
export default router;
